version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  golang-python-app:
    build:
      context: .
    expose:
      - 8080
    ports:
      - "8081-8085:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 5

  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - golang-python-app